[build]
  command = "npm run build"
  publish = ".next"
  environment = { GIT_SSH_COMMAND = "ssh -i /opt/buildhome/.ssh/NETLIFY_DEPLOY_KEY -o StrictHostKeyChecking=no" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200