[build]
  command = "npm run build"
  publish = ".next"
  environment = { NEXT_PUBLIC_VISUAL_EDITOR = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200