name: Auto Merge Between Main and Preview

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Git
      run: |
        git config user.name "patrlckroe"
        git config user.email "pat10roe@icloud.com"

    - name: Fetch branches
      run: git fetch origin +refs/heads/*:refs/remotes/origin/*

    - name: Merge branches
      run: |
        git checkout -b preview origin/preview || git checkout preview
        git merge origin/main --allow-unrelated-histories --no-edit
        git push origin preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
