name: Auto Merge Between Main and Preview

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false # Ensure the token is not persisted

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch branches
      run: git fetch origin +refs/heads/*:refs/remotes/origin/*

    - name: Merge branches
      run: |
        git checkout preview
        git merge origin/main
        git push origin preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
