name: Auto Merge Between Main and Preview

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false # Ensure the token is not persisted

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Fetch branches
      run: git fetch origin +refs/heads/*:refs/remotes/origin/*

    - name: Sync Preview with Main
      run: |
        # Checkout the preview branch, create it if it doesn't exist
        git checkout preview || git checkout -b preview
        
        # Reset the preview branch to match main
        git reset --hard origin/main
        
        # Push the changes to the preview branch
        git push origin preview --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
